version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
  
  test:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=test
    command: npm test
    depends_on:
      - app

  production:
    build:
      context: .
      target: production
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    command: npm start
    depends_on:
      - test